#!/usr/bin/env python3
"""
수집된 Rust 업데이트를 Claude API로 분석하여
현재 rules에 반영해야 할 사항을 PR body로 제안.

⚠️  이 스크립트는 rules를 직접 수정하지 않음.
    PR body로 제안 → 사람이 검토 후 머지.
"""

import os
import anthropic
from pathlib import Path

UPDATES_FILE = os.environ.get("UPDATES_FILE", "/tmp/rust_updates.md")
OUTPUT_FILE  = os.environ.get("OUTPUT_FILE",  "/tmp/rule_suggestions.md")

# 현재 rules 파일들을 읽어 Claude에게 컨텍스트로 제공
RULES_FILES = [
    "_common/base.rules.md",
    "_common/tdd.rules.md",
    "web-axum/.gemini/GEMINI.md",
    "embedded/.gemini/GEMINI.md",
    "systems-cli/.gemini/GEMINI.md",
]


def load_current_rules() -> str:
    parts = []
    for path in RULES_FILES:
        p = Path(path)
        if p.exists():
            parts.append(f"### {path}\n```\n{p.read_text()}\n```")
    return "\n\n".join(parts)


def main():
    updates = Path(UPDATES_FILE).read_text()
    if not updates.strip():
        print("No updates fetched. Skipping.")
        return

    current_rules = load_current_rules()

    client = anthropic.Anthropic()

    prompt = f"""You are a Rust ecosystem expert reviewing AI coding rules templates.

Here are the current rules:

{current_rules}

---

Here are this week's Rust ecosystem updates:

{updates}

---

Your task:
1. Identify if any updates suggest rules changes:
   - New crate versions with breaking changes or important new features
   - New Rust language features relevant to the coding patterns
   - New best practices or deprecations in key crates (axum, tokio, sqlx, embassy)
   - Security advisories affecting dependencies in the rules

2. For each relevant finding, suggest a specific rule change.

Format your response as a GitHub PR body in Markdown:
- Start with an executive summary (2-3 sentences)
- List findings as ## sections
- For each finding: what changed, which rule file to update, exact suggested text
- If nothing needs updating, say "No rule changes needed this week" and explain why
- Keep suggestions conservative — only suggest changes that are clearly beneficial and verified
- Do NOT suggest speculative or uncertain changes

Be concise. Prioritize actionable suggestions."""

    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )

    suggestion = message.content[0].text

    # PR body에 메타데이터 추가
    pr_body = f"""<!-- Auto-generated by weekly-rules-update workflow -->
<!-- Review carefully before merging. Do NOT merge without human review. -->

{suggestion}

---

> 📋 **검토 체크리스트**
> - [ ] 제안된 변경사항이 실제로 필요한가?
> - [ ] 변경사항이 기존 rules와 일관성이 있는가?
> - [ ] 모든 도메인 파일에 동일하게 반영했는가?
> - [ ] 변경 후 example 코드가 여전히 컴파일되는가?
"""

    # "No rule changes" 면 PR 생성 안 함
    if "No rule changes needed" in suggestion:
        print("No rule changes needed this week.")
        Path(OUTPUT_FILE).write_text("")  # 빈 파일 → check step이 false 반환
        return

    Path(OUTPUT_FILE).write_text(pr_body)
    print(f"Wrote PR body to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
