#!/usr/bin/env python3
"""
Rust 에코시스템 업데이트를 AI로 분석 → PR body 제안.

AI 제공자 우선순위:
  1순위: Anthropic API  (ANTHROPIC_API_KEY 설정 시)
  2순위: Google Gemini  (GEMINI_API_KEY 설정 시)
"""

import os
import sys
from pathlib import Path

UPDATES_FILE = os.environ.get("UPDATES_FILE", "/tmp/rust_updates.md")
OUTPUT_FILE  = os.environ.get("OUTPUT_FILE",  "/tmp/rule_suggestions.md")

RULES_FILES = [
    "_common/base.rules.md",
    "_common/tdd.rules.md",
    "web-axum/.gemini/GEMINI.md",
    "embedded/.gemini/GEMINI.md",
    "systems-cli/.gemini/GEMINI.md",
]

PROMPT_TEMPLATE = """\
You are a Rust ecosystem expert reviewing AI coding rules templates.

Here are the current rules:

{current_rules}

---

Here are this week's Rust ecosystem updates:

{updates}

---

Your task:
1. Identify if any updates suggest rules changes:
   - New crate versions with breaking changes or important new features
   - New Rust language features relevant to the coding patterns
   - New best practices or deprecations in key crates (axum, tokio, sqlx, embassy)
   - Security advisories affecting dependencies in the rules

2. For each relevant finding, suggest a specific rule change.

Format your response as a GitHub PR body in Markdown:
- Start with an executive summary (2-3 sentences)
- List findings as ## sections
- For each finding: what changed, which rule file to update, exact suggested text
- If nothing needs updating, say "No rule changes needed this week" and explain why
- Keep suggestions conservative - only suggest clearly beneficial, verified changes
- Do NOT suggest speculative or uncertain changes

Be concise. Prioritize actionable suggestions."""


def load_current_rules() -> str:
    parts = []
    for path in RULES_FILES:
        p = Path(path)
        if p.exists():
            parts.append(f"### {path}\n```\n{p.read_text()}\n```")
    return "\n\n".join(parts)


def call_anthropic(prompt: str) -> str:
    import anthropic
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text


def call_gemini(prompt: str) -> str:
    import google.generativeai as genai
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])
    model = genai.GenerativeModel("gemini-2.0-flash")
    response = model.generate_content(prompt)
    return response.text


def get_suggestion(prompt: str) -> tuple[str, str]:
    """
    AI 호출 시도. (response_text, used_provider) 반환.
    1순위 Anthropic → 실패 시 Gemini 폴백.
    """
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")
    gemini_key    = os.environ.get("GEMINI_API_KEY", "")

    if not anthropic_key and not gemini_key:
        print("ERROR: ANTHROPIC_API_KEY 또는 GEMINI_API_KEY 중 하나는 설정해야 합니다.", file=sys.stderr)
        sys.exit(1)

    # 1순위: Anthropic
    if anthropic_key:
        try:
            print("[AI] Anthropic API 시도 중...")
            result = call_anthropic(prompt)
            print("[AI] Anthropic API 성공.")
            return result, "Anthropic (claude-opus-4-6)"
        except Exception as e:
            print(f"[AI] Anthropic 실패: {e}")
            if not gemini_key:
                print("ERROR: Gemini fallback key도 없습니다.", file=sys.stderr)
                sys.exit(1)
            print("[AI] Gemini API로 폴백...")

    # 2순위: Gemini
    if gemini_key:
        try:
            print("[AI] Gemini API 시도 중...")
            result = call_gemini(prompt)
            print("[AI] Gemini API 성공.")
            return result, "Google Gemini (gemini-2.0-flash)"
        except Exception as e:
            print(f"ERROR: Gemini도 실패: {e}", file=sys.stderr)
            sys.exit(1)

    print("ERROR: 사용 가능한 AI 제공자 없음.", file=sys.stderr)
    sys.exit(1)


def main():
    updates = Path(UPDATES_FILE).read_text()
    if not updates.strip():
        print("No updates fetched. Skipping.")
        return

    current_rules = load_current_rules()
    prompt = PROMPT_TEMPLATE.format(
        current_rules=current_rules,
        updates=updates,
    )

    suggestion, provider = get_suggestion(prompt)

    # "No rule changes"면 빈 파일 → PR 생성 안 함
    if "No rule changes needed" in suggestion:
        print(f"No rule changes needed this week. (via {provider})")
        Path(OUTPUT_FILE).write_text("")
        return

    pr_body = f"""<!-- Auto-generated by weekly-rules-update workflow -->
<!-- AI provider used: {provider} -->
<!-- Review carefully before merging. Do NOT merge without human review. -->

{suggestion}

---

> 📋 **검토 체크리스트** (via {provider})
> - [ ] 제안된 변경사항이 실제로 필요한가?
> - [ ] 변경사항이 기존 rules와 일관성이 있는가?
> - [ ] 모든 도메인 파일에 동일하게 반영했는가?
> - [ ] 변경 후 example 코드가 여전히 컴파일되는가?
"""

    Path(OUTPUT_FILE).write_text(pr_body)
    print(f"Wrote PR body to {OUTPUT_FILE} (via {provider})")


if __name__ == "__main__":
    main()
